var hoursLabel = document.getElementById('hours');
var minutesLabel = document.getElementById('minutes');
var secondsLabel = document.getElementById('seconds');
var decsLabel = document.getElementById('decs');
setInterval(doTime, 100);
synctimer = setTimeout(dosync, 2200);
var decsLabel = document.getElementById('decs');
var falLabel = document.getElementById('fal');
var sucLabel = document.getElementById('suc');
var preLabel = document.getElementById('pre');
var ofsLabel = document.getElementById('ofs');
var lteLabel = document.getElementById('lte');
var offsetfix = 0;
document.getElementById('momenttime').innerHTML='In moment when this page was generated, the time was <b>'+new Date(client-offsetfix)+'</b>';
